import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/main.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MisterTelescope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " light-theme"}>{children}</body>
    </html>
  );
}