import type { Metadata } from "next";
import "./../css/main.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <div className="light-theme">{children}</div>
    );
  }